/* tslint:disable */
/* eslint-disable */
/**
 * NexTrip API
 * API for creating Metro Transit real-time departure information display (beta, subject to change)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

